

export const banks = [
    {
        "code": "MB2U0227",
        "name": "Maybank2U",
        "img": "https://cdn.freebiesupply.com/logos/large/2x/maybank-logo-black-and-white.png",
        "backgroundColor": '#f7c000',
        "textColor": 'black',
    },
    {
        "code": "BCBB0235",
        "name": "CIMB Clicks",
        "img": "https://pngimage.net/wp-content/uploads/2018/05/cimb-click-logo-png-4.png",
        "backgroundColor": '#ed1c24',
        "textColor": 'white',
    },
    {
        "code": "RHB0218",
        "name": "RHB Now",
        "img": "",
        "backgroundColor": '#6ccee6',
        "textColor": '#0067B0',
    },
    {
        "code": "PBB0233",
        "name": "Public Bank",
        "img": "",
        "backgroundColor": 'white',
        "textColor": '#e61a23',
    },
    {
        "code": "HLB0224",
        "name": "Hong Leong Bank",
        "img": "",
        "backgroundColor": 'white',
        "textColor": '#002147',
    },
    {
        "code": "ABB0233",
        "name": "Affin Bank",
        "img": "",
        "backgroundColor": '#004c98',
        "textColor": 'white',
    },
    {
        "code": "ABMB0212",
        "name": "Alliance Bank",
        "img": "",
        "backgroundColor": 'white',
        "textColor": '#004c98',
    },
    {
        "code": "AMBB0209",
        "name": "AmBank",
        "img": "",
        "backgroundColor": '#ed1b23',
        "textColor": '#fff200',
    },
    {
        "code": "BIMB0340",
        "name": "Bank Islam",
        "img": "",
        "backgroundColor": '#9880a5',
        "textColor": 'white',
    },
    {
        "code": "BMMB0341",
        "name": "Bank Muamalat",
        "img": "",
        "backgroundColor": '#004b92',
        "textColor": 'white',
    },
    {
        "code": "BKRM0602",
        "name": "Bank Rakyat",
        "img": "",
        "backgroundColor": '#165ca7',
        "textColor": 'white',
    },
    {
        "code": "BSN0601",
        "name": "BSN",
        "img": "",
        "backgroundColor": '#00a2b1',
        "textColor": 'white',
    },
    {
        "code": "HSBC0223",
        "name": "HSBC Bank",
        "img": "",
        "backgroundColor": '#da0011',
        "textColor": 'white',
    },
    {
        "code": "KFH0346",
        "name": "Kuwait Finance House",
        "img": "",
        "backgroundColor": 'white',
        "textColor": '#09934c',
    },
    {
        "code": "OCBC0229",
        "name": "OCBC Bank",
        "img": "",
        "backgroundColor": 'white',
        "textColor": '#ee2722',
    },
    {
        "code": "SCB0216",
        "name": "Standard Chartered",
        "img": "",
        "backgroundColor": 'white',
        "textColor": '#0072aa',
    },
    {
        "code": "UOB0226",
        "name": "UOB Bank",
        "img": "",
        "backgroundColor": '#2d3365',
        "textColor": 'white',
    },
    {
        "code": "MBB0228",
        "name": "Maybank Enterprise",
        "img": "",
        "backgroundColor": '#f7c000',
        "textColor": 'black',
    }
]

